---
# cloudbuild-frontend.yaml
# Use this for fast frontend-only deployments.
# Command: gcloud builds submit --config cloudbuild-frontend.yaml .

steps:
  # Build and deploy the frontend assets service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Build Frontend Assets'
    args:
      - 'build'
      - '-t'
      - 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/swarmmap-repo/frontend:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'Push Frontend Assets'
    args:
      - 'push'
      - 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/swarmmap-repo/frontend:latest'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'Deploy Frontend Assets'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'utba-swarmmap-frontend'
      - '--image=northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/swarmmap-repo/frontend:latest'
      - '--region=northamerica-northeast2'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--quiet'

images:
  - 'northamerica-northeast2-docker.pkg.dev/$PROJECT_ID/swarmmap-repo/frontend:latest'
options:
  logging: CLOUD_LOGGING_ONLY
