// Copyright (c) 2026 Frank Currie (frank@sfle.ca)

package handlers

import (
	"bytes"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"
)

type FeedbackRequest struct {
	Type        string          `json:"type"`
	Title       string          `json:"title"`
	Description string          `json:"description"`
	Context     FeedbackContext `json:"context"`
}

type FeedbackContext struct {
	URL      string `json:"url"`
	Browser  string `json:"browser"`
	LoggedIn bool   `json:"loggedIn"`
}

// GitHubService defines the interface for GitHub operations.
type GitHubService interface {
	CreateIssue(repo, token, title, body string, labels []string) error
}

// RealGitHubService implements GitHubService using the GitHub API.
type RealGitHubService struct {
	Client *http.Client
}

func (s *RealGitHubService) CreateIssue(repo, token, title, body string, labels []string) error {
	url := fmt.Sprintf("https://api.github.com/repos/%s/issues", repo)

	payload := map[string]interface{}{
		"title":  title,
		"body":   body,
		"labels": labels,
	}

	jsonPayload, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("failed to marshal GitHub payload: %w", err)
	}

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonPayload))
	if err != nil {
		return fmt.Errorf("failed to create GitHub request: %w", err)
	}

	req.Header.Set("Authorization", "token "+token)
	req.Header.Set("Accept", "application/vnd.github.v3+json")
	req.Header.Set("Content-Type", "application/json")

	resp, err := s.Client.Do(req)
	if err != nil {
		return fmt.Errorf("failed to send GitHub request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusCreated {
		var respBody bytes.Buffer
		_, _ = respBody.ReadFrom(resp.Body)
		return fmt.Errorf("GitHub API returned non-201 status: %d, body: %s", resp.StatusCode, respBody.String())
	}

	return nil
}

func (h *Handlers) FeedbackHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		h.jsonError(w, "Only POST method is allowed", http.StatusMethodNotAllowed)
		return
	}

	var req FeedbackRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		slog.Error("Failed to decode feedback request", "error", err)
		h.jsonError(w, "Invalid request payload", http.StatusBadRequest)
		return
	}

	if req.Title == "" || req.Description == "" {
		h.jsonError(w, "Title and description are required", http.StatusBadRequest)
		return
	}

	if h.GithubToken == "" {
		slog.Error("GITHUB_TOKEN not configured")
		h.jsonError(w, "GitHub integration not configured", http.StatusServiceUnavailable)
		return
	}

	repo := h.GithubRepo
	if repo == "" {
		repo = "fkcurrie/utba-swarmmap"
	}

	issueBody := fmt.Sprintf(`## User Feedback

**Type:** %s
**Reported From:** %s
**Logged In:** %v
**Browser:** %s

### Description
%s

---
Generated by **Overseer** (powered by the gemini-3-flash-preview model).`,
		req.Type,
		req.Context.URL,
		req.Context.LoggedIn,
		req.Context.Browser,
		req.Description,
	)

	labels := []string{"repo-agent", req.Type}

	// Use GitHubService if available, otherwise fall back to internal implementation
	// For now, we assume it's always configured in main.go
	if h.GitHubService != nil {
		err := h.GitHubService.CreateIssue(repo, h.GithubToken, req.Title, issueBody, labels)
		if err != nil {
			slog.Error("Failed to create GitHub issue via service", "error", err)
			h.jsonError(w, "Failed to create GitHub issue", http.StatusInternalServerError)
			return
		}
	} else {
		slog.Error("GitHubService not initialized")
		h.jsonError(w, "GitHub integration not initialized", http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(map[string]string{"status": "success"}); err != nil {
		slog.Error("Failed to encode success response", "error", err)
	}
}
