// Copyright (c) 2026 Frank Currie (frank@sfle.ca)

package handlers

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"net/http"

	"cloud.google.com/go/vertexai/genai"
)

type FeedbackRequest struct {
	Type        string          `json:"type"`
	Title       string          `json:"title"`
	Description string          `json:"description"`
	Context     FeedbackContext `json:"context"`
}

type FeedbackContext struct {
	URL      string `json:"url"`
	Browser  string `json:"browser"`
	LoggedIn bool   `json:"loggedIn"`
}

// VertexAIService implements AIService using Google Cloud Vertex AI Gemini.
type VertexAIService struct {
	Client *genai.Client
	Model  string
}

func (s *VertexAIService) InterpretFeedback(ctx context.Context, rawText string, feedbackType string, fbCtx FeedbackContext) (string, error) {
	model := s.Client.GenerativeModel(s.Model)

	prompt := fmt.Sprintf(`You are a Product Manager and QA Engineer. Your task is to take raw user feedback from a web application called "UTBA Swarm Map" and turn it into a professional, actionable GitHub issue.

Input:
- Feedback Type: %s
- Raw Description: %s
- URL: %s
- Browser: %s
- Logged In: %v

Output Format:
Please provide a structured markdown issue with the following sections:
## Summary
A concise one-sentence summary of the issue.

## Interpreted Intent
Explain what the user was likely trying to achieve or report, even if their language was vague.

## Context
- **Type:** %s
- **URL:** %s
- **Browser:** %s
- **Logged In:** %v

## Technical Impact
Deduce the likely technical impact on the system or user experience.

## Actionable Steps
Provide a list of steps for developers to reproduce or investigate the issue.

Maintain a professional and constructive tone. Do not include any other text than the markdown content.`,
		feedbackType, rawText, fbCtx.URL, fbCtx.Browser, fbCtx.LoggedIn,
		feedbackType, fbCtx.URL, fbCtx.Browser, fbCtx.LoggedIn,
	)

	resp, err := model.GenerateContent(ctx, genai.Text(prompt))
	if err != nil {
		return "", fmt.Errorf("failed to generate content with Gemini: %w", err)
	}

	if resp == nil || len(resp.Candidates) == 0 || len(resp.Candidates[0].Content.Parts) == 0 {
		return "", fmt.Errorf("empty response from Gemini")
	}

	var interpreted string
	for _, part := range resp.Candidates[0].Content.Parts {
		if text, ok := part.(genai.Text); ok {
			interpreted += string(text)
		}
	}

	interpreted += "\n\n---\nGenerated by **Overseer** (powered by Gemini)."

	return interpreted, nil
}

// GitHubService defines the interface for GitHub operations.
type GitHubService interface {
	CreateIssue(repo, token, title, body string, labels []string) error
}

// RealGitHubService implements GitHubService using the GitHub API.
type RealGitHubService struct {
	Client *http.Client
}

func (s *RealGitHubService) CreateIssue(repo, token, title, body string, labels []string) error {
	url := fmt.Sprintf("https://api.github.com/repos/%s/issues", repo)

	payload := map[string]interface{}{
		"title":  title,
		"body":   body,
		"labels": labels,
	}

	jsonPayload, err := json.Marshal(payload)
	if err != nil {
		return fmt.Errorf("failed to marshal GitHub payload: %w", err)
	}

	req, err := http.NewRequest("POST", url, bytes.NewBuffer(jsonPayload))
	if err != nil {
		return fmt.Errorf("failed to create GitHub request: %w", err)
	}

	req.Header.Set("Authorization", "token "+token)
	req.Header.Set("Accept", "application/vnd.github.v3+json")
	req.Header.Set("Content-Type", "application/json")

	resp, err := s.Client.Do(req)
	if err != nil {
		return fmt.Errorf("failed to send GitHub request: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusCreated {
		var respBody bytes.Buffer
		_, _ = respBody.ReadFrom(resp.Body)
		return fmt.Errorf("GitHub API returned non-201 status: %d, body: %s", resp.StatusCode, respBody.String())
	}

	return nil
}

func (h *Handlers) FeedbackHandler(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		h.jsonError(w, "Only POST method is allowed", http.StatusMethodNotAllowed)
		return
	}

	var req FeedbackRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		slog.Error("Failed to decode feedback request", "error", err)
		h.jsonError(w, "Invalid request payload", http.StatusBadRequest)
		return
	}

	if req.Title == "" || req.Description == "" {
		h.jsonError(w, "Title and description are required", http.StatusBadRequest)
		return
	}

	if h.GithubToken == "" {
		slog.Error("GITHUB_TOKEN not configured")
		h.jsonError(w, "GitHub integration not configured", http.StatusServiceUnavailable)
		return
	}

	repo := h.GithubRepo
	if repo == "" {
		repo = "fkcurrie/utba-swarmmap"
	}

	var issueBody string
	var err error

	if h.AIService != nil {
		issueBody, err = h.AIService.InterpretFeedback(r.Context(), req.Description, req.Type, req.Context)
		if err != nil {
			slog.Warn("AI interpretation failed, falling back to raw feedback", "error", err)
		}
	}

	if issueBody == "" {
		issueBody = fmt.Sprintf(`## User Feedback

**Type:** %s
**Reported From:** %s
**Logged In:** %v
**Browser:** %s

### Description
%s

---
Generated by **Overseer** (powered by the gemini-3-flash-preview model).`,
			req.Type,
			req.Context.URL,
			req.Context.LoggedIn,
			req.Context.Browser,
			req.Description,
		)
	}

	labels := []string{"repo-agent", req.Type}

	// Use GitHubService if available, otherwise fall back to internal implementation
	// For now, we assume it's always configured in main.go
	if h.GitHubService != nil {
		err := h.GitHubService.CreateIssue(repo, h.GithubToken, req.Title, issueBody, labels)
		if err != nil {
			slog.Error("Failed to create GitHub issue via service", "error", err)
			h.jsonError(w, "Failed to create GitHub issue", http.StatusInternalServerError)
			return
		}
	} else {
		slog.Error("GitHubService not initialized")
		h.jsonError(w, "GitHub integration not initialized", http.StatusInternalServerError)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	if err := json.NewEncoder(w).Encode(map[string]string{"status": "success"}); err != nil {
		slog.Error("Failed to encode success response", "error", err)
	}
}
