steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/utba-swarmmap', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/utba-swarmmap']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'utba-swarmmap'
      - '--image'
      - 'gcr.io/$PROJECT_ID/utba-swarmmap'
      - '--region'
      - 'northamerica-northeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-secrets'
      - '/app/service-account-key.json=swarmmap-service-account:latest'
      - '--set-env-vars'
      - 'GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-key.json'

images:
  - 'gcr.io/$PROJECT_ID/utba-swarmmap' 