#!/bin/bash
# Copyright (c) 2026 Frank Currie (frank@sfle.ca)

set -e

SERVICE=$1
FRONTEND_SERVICE=$2
REGION=$3
DEPLOYED_URL=$4
GITHUB_TOKEN=$5
SHA=$6

echo "Deployment validation failed for $SERVICE at $DEPLOYED_URL"
echo "Initiating rollback..."

# Rollback Backend
echo "Rolling back Backend service: $SERVICE..."
gcloud run services rollback $SERVICE --region=$REGION --quiet || echo "Backend rollback failed (maybe no previous revision)"

# Rollback Frontend
echo "Rolling back Frontend service: $FRONTEND_SERVICE..."
gcloud run services rollback $FRONTEND_SERVICE --region=$REGION --quiet || echo "Frontend rollback failed (maybe no previous revision)"

echo "Rollback complete."

# Create GitHub Issue
echo "Creating GitHub Issue..."

ISSUE_TITLE="Deployment Validation Failed: $SHA"
ISSUE_BODY="## Deployment Validation Failed

The post-deployment validation for the latest release (commit $SHA) failed. 
Cloud Run services have been automatically rolled back to the previous stable revision.

**Service:** $SERVICE
**Region:** $REGION
**URL Checked:** $DEPLOYED_URL

### Failure Details
Please check the [GitHub Actions run logs](https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}) for details on the failed Playwright tests and to view screenshots of the failure.

Generated by **Overseer** (powered by the gemini-3-flash-preview model)."

gh issue create \
  --title "$ISSUE_TITLE" \
  --body "$ISSUE_BODY" \
  --label "overseer" \
  --label "bug"

echo "GitHub Issue created."
