# Copyright (c) 2026 Frank Currie (frank@sfle.ca)
---
name: Deploy to Cloud Run

on:
  workflow_dispatch:

env:
  PROJECT_ID: utba-swarmmap
  REGION: northamerica-northeast2
  SERVICE: utba-swarmmap-backend
  FRONTEND_SERVICE: utba-swarmmap-frontend
  REPO: swarmmap-repo
  GCS_BUCKET_NAME: utba-swarmmap-media

jobs:
  deploy:
    name: Validate, Build, and Deploy
